### ISSUE TITLE
Package fails to resolve dependencies from "path"

### ISSUE THREAD

**Issue by johnmorrell** [noppoMan/Hexaville#117]
Dependencies from a url, eg:

`.package(url: "https://github.com/noppoMan/HexavilleFramework.git", .upToNextMajor(from: "1.0.0-rc.3"))`

resolves and packages correctly, but from a local path, eg:

`.package(path: "../LocalPackage")`

package fails and the following error is returned:

`error: /LocalPackage has no manifest`

Running `swift build` is successful.

**Comment by noppoMan** [comment]
@johnmorrell  Can I close this?

**Comment by johnmorrell** [comment]
Yes, I think I this is an issue with filesystem access from Docker. I need to move the swift package to its own repo.
