### ISSUE TITLE
Support swift 5.1

### ISSUE THREAD

**Issue by johnmorrell** [noppoMan/Hexaville#118]
I would really appreciate support for swift 5.1. I have been attempting to work with 4.2, but experiencing a crash running on lambda:

`Fatal error: : file Foundation/NSCalendar.swift, line 617`

I get this during any attempt to create a date object from a time interval, calendar or string. This appears to be a known and resolved bug in swift on linux and works as expected running on Mac.

**Comment by noppoMan** [comment]
@johnmorrell Sorry for late reply.
I've just started to support swift 5.1! Please give me a little time.

> Fatal error: : file Foundation/NSCalendar.swift, line 617
hmmm. I've never used NSCalendar on lambda So, I'll also investigate this error with swift 5.1 supporting.

**Comment by johnmorrell** [comment]
Thank you @noppoMan.

Strangely after a number of deployments, I have just stopped seeing that error under Swift 4.2, so I am no longer sure of the cause.

Support for Swift 5.1 is still much appreciated.

**Comment by noppoMan** [comment]
@johnmorrell I've finished to support Swift 5.1 and It seems to work well!
Here is the test commands I tried.

```sh
rm -rf ~/.hexaville
curl -L https://rawgit.com/noppoMan/Hexaville/master/install.sh | bash
hexaville generate Swift5Example -o /Users/yuki/Desktop
cd Swift5Example
hexaville package
serverless deploy --stage staging 
```

I hope it works well.

**Comment by noppoMan** [comment]
And one more. I added following middleware into Swift5Example's main.swift

```swift
app.use { request, context in
    let cal = NSCalendar(identifier: NSCalendar.Identifier.gregorian)
    print(cal?.component(.month, from: Date()))
    return .next(request)
}
```
After deployed it, I got `Optional(9)` on console of CloudWatchLogs. So I think NSCalendar works fine with Swift 5.1.

**Comment by johnmorrell** [comment]
Looks great on 5.1. I was also experiencing a strange lib dependency error with 4.2 yesterday in certain code paths, but that now also seems fixed.

Thank you!

**Comment by noppoMan** [comment]
good to hear! I hope your research goes well with Hexaville!
