### ISSUE TITLE
`$ Hexaville deploy <ProjectName>` fails with `InvalidBucketName`

### ISSUE THREAD

**Issue by mitsuyoshi-yamazaki** [noppoMan/Hexaville#17]
# Agenda

Same as title.
See [Error logs](#error_logs) for detail.

# How to reproduce

Follow the instructions in https://medium.com/@yukitakei/serverless-server-side-swift-with-hexaville-ef0e1788a20 until "Deploy" section.

# Error logs
<a name="error_logs"></a>

```shell
$ path/to/Hexaville deploy Hello
...
Uploading code to s3.....
AWSResponseError(errorCode: "InvalidBucketName", message: Optional("The specified bucket is not valid."))
An error occurred: The operation couldn’t be completed. (Core.AWSResponseError error 1.)
```

# How to resolved

The bucket name was `hexaville-Hello-bucket`.

It was said..

```
Bucket name should conform with DNS requirements: 
- Should not contain uppercase characters <- !!
- Should not contain underscores (_)
- Should be between 3 and 63 characters long
- Should not end with a dash
- Cannot contain two, adjacent periods
- Cannot contain dashes next to periods (e.g., "my-.bucket.com" and "my.-bucket" are invalid)

# https://forums.aws.amazon.com/message.jspa?messageID=315883
```

I changed `Hello` -> `hello` in 
- `name` property in Hexavillefile.yml
- `deploy` command's argument `$ Hexaville deploy hello`

then the error disappeared.

# 追記

書いてて思いましたがMediumの方（プロジェクト名を `Hello` にしている部分）を直すべきかも

**Comment by noppoMan** [comment]
Thanks again!

Actually I fixed this problem in https://github.com/noppoMan/Hexaville/pull/13
So Could you update Hexaville with git pull or something?

Now Bucket name format is integrated to lowercase.　https://github.com/noppoMan/Hexaville/blob/master/Sources/Hexaville/main.swift#L65

And `aws.lambda.bucket` became required param.
```yml
name: test-app
....
  lambda:
    bucket: here is generated automatically when your Hexaville version is 0.1.4 or later
    role: xxxxxxxxx
```
